version: 1.1.{build}
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - git config --global core.autocrlf true
before_build:
  # Display minimal restore text
  - cmd: dotnet restore ./Audecyzje.API/Audecyzje.API/Audecyzje.API.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./Audecyzje.API/Audecyzje.API/Audecyzje.API.csproj
artifacts:
 - path: '\src\bin\Debug\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
deploy:
- provider: Environment
  name: Development